### ISSUE TITLE
Clash Royale 

### ISSUE THREAD

**Issue by tayyabkhan52** [Gr8z/Legend-Cogs#1]
Import Error: No module named 'crapipy' 
It is isnt loading because of this error what is the issue?
![image](https://user-images.githubusercontent.com/23267763/32570955-c7d4d3ce-c4bd-11e7-83c3-7cb77872f101.png)

![image](https://user-images.githubusercontent.com/23267763/32571028-fc373d14-c4bd-11e7-8b83-1f51e07d8a66.png)

**Comment by Gr8z** [comment]
Please run this command to install crapipy

`pip install crapipy`
