### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rodelfard** [Gr8z/Legend-Cogs#51]
Hello,
I congratulate you on the work you have done!

http://prntscr.com/l092nk

I've tried installing the various "cogs" but I can not!
I can only install the "crtools"

can you help me?

**Comment by rodelfard** [comment]
python --version
Python 3.5.4

pip --version
pip 18.0 from c:\users\gonfe\appdata\local\programs\python\python35\lib\site-packages\pip (python 3.5)

**Comment by Gr8z** [comment]
Please update your pip to the latest version and update to python 3.6

**Comment by rodelfard** [comment]
python 3.6.0 

pip...
C:\Users\Gonfe>python -m pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-18.0


I continue with the same error. What happened?

Sorry for the inconvenience.

**Comment by rodelfard** [comment]
Downloading https://files.pythonhosted.org/packages/1b/50/869910cd7110157fbefd0fed3db3656c1951f1bceecdd00e3716aa269609/Pillow-5.2.0-cp36-cp36m-win_amd64.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 1.5MB/s
Installing collected packages: Pillow
Successfully installed Pillow-5.2.0
Collecting clashroyale
  Using cached https://files.pythonhosted.org/packages/ff/25/a963cac6bbd14373d53f962969ba7cf771d32a57e09d247b490c003cb9d9/clashroyale-3.5.14.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\clashroyale.egg-info
    writing pip-egg-info\clashroyale.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\clashroyale.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\clashroyale.egg-info\requires.txt
    writing top-level names to pip-egg-info\clashroyale.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\clashroyale.egg-info\SOURCES.txt'
    C:\Users\Gonfe\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    C:\Users\Gonfe\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing 'v3.5.14' to '3.5.14'
      normalized_version,
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\clashroyale.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info\clashroyale.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Gonfe\AppData\Local\Temp\pip-install-gd3drg3f\clashroyale\setup.py", line 34, in <module>
        data = json.loads(urllib.request.urlopen('https://fourjr-webserver.herokuapp.com/cr/constants').read())
      File "C:\Users\Gonfe\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\Gonfe\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
        response = meth(req, response)
      File "C:\Users\Gonfe\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "C:\Users\Gonfe\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
        return self._call_chain(*args)
      File "C:\Users\Gonfe\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
        result = func(*args)
      File "C:\Users\Gonfe\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 503: Service Unavailable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Gonfe\AppData\Local\Temp\pip-install-gd3drg3f\clashroyale\

**Comment by Gr8z** [comment]
It looks like there is a problem with installing clashroyale library. Can you try downgrading it and see if the issue persists?

https://github.com/cgrok/clashroyale

**Comment by DurzoB5** [comment]
There is an issue for this on the clashroyale repo. The Heroku app it loads data from is currently broken so install fails. https://github.com/cgrok/clashroyale/issues/27

**Comment by Gr8z** [comment]
Yes, but you can downgrade the library to the version that didnt include the URL.

**Comment by rodelfard** [comment]
http://prntscr.com/l0fds6

by "cmd"

Am I doing something wrong?

I'm really sorry for the inconvenience.

**Comment by Gr8z** [comment]
`pip install https://files.pythonhosted.org/packages/fa/67/f4aa76b75b1dfc8dc83f4492cb84ec7ece8c7df86a046a96c11bbba3d2c3/clashroyale-3.5.10.tar.gz`

**Comment by rodelfard** [comment]
http://prntscr.com/l0fit9

another error.

once again I apologize for the inconvenience,
In the end, I wanted to ask you for your paypal account. To thank you!

sorry for my english xd

**Comment by rodelfard** [comment]
C:\WINDOWS\system32>pip --version
pip 18.0 from c:\users\gonfe\appdata\local\programs\python\python36\lib\site-packages\pip (python 3.6)

C:\WINDOWS\system32>python --version
Python 3.6.0

**Comment by Gr8z** [comment]
No problem, the `clashroyale` author told me he will fix this tomorrow.

**Comment by rodelfard** [comment]
I only have to do what tomorrow?

!cog install Legend-Cogs clashroyale (discord)

or....

pip install https://files.pythonhosted.org/packages/fa/67/f4aa76b75b1dfc8dc83f4492cb84ec7ece8c7df86a046a96c11bbba3d2c3/clashroyale-3.5.10.tar.gz
(cmd)

?

**Comment by Gr8z** [comment]
Do pip install -U clashroyale

when there is a new update tomorrow

**Comment by fourjr** [comment]
should be up a few hours ago
