### ISSUE TITLE
Repo is weird.. doesn't seem to work.

### ISSUE THREAD

**Issue by Mrs-Feathers** [Gr8z/Legend-Cogs#54]
It doesn't see a cog in your github that there obviously is... 
<img width="407" alt="Screen Shot 2019-04-30 at 18 06 35" src="https://user-images.githubusercontent.com/1746550/56996496-b6dea880-6b72-11e9-8bdf-937b555afdc0.png">
<img width="458" alt="Screen Shot 2019-04-30 at 18 08 01" src="https://user-images.githubusercontent.com/1746550/56996559-ec839180-6b72-11e9-94b5-449aefab0780.png">

**Comment by kingsleyzhong** [comment]
What RED version are you using, I'm not too familiar with it. Also, would you mind DMing me on discord at @Generaleoley#4249, we can try to sort it out there.

**Comment by Mrs-Feathers** [comment]
I found out why. Just starting to code. The info.js is different on V3 so it doesn’t recognize. I learned that like this morning. Lol

———
73, KC1KSG

**Comment by Mrs-Feathers** [comment]
I tried cloning a few other repos of cogs To learn from it and I found that out Because some of them worked in some of them didn’t

———
73, KC1KSG

**Comment by kingsleyzhong** [comment]
Well Great! This is a V2 cog so it won't work for V3.

**Comment by Mrs-Feathers** [comment]
Yeah. Found that out after the fact. Still great material to learn python from, keeping in mind what’s different and what’s not of the v2 and v3 cog api

———
73, KC1KSG

**Comment by Gr8z** [comment]
These are v2 cogs, not yet compatible with Red v3
